spring:
  application:
    name: back_zipt
  profiles:
    active: dev          # 로컬 개발 시 dev / 배포 시 prod로 변경 / H2 테스트 local
  #ocr 파일 크기 늘림
  config:
    import: "optional:classpath:application-dev.yml"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    hikari:
      leak-detection-threshold: 2000
      maximum-pool-size: 20
      connection-timeout: 30000

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  # pgvector 커스텀 vectorstore 사용을 위해 exclude
  autoconfigure:
    exclude:
      - org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration


# CORS
cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

# AWS S3 & Cloud
cloud:
  aws:
    region:
      static: ${AWS_REGION:ap-northeast-2}
    credentials:
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}
    s3:
      bucket-files: ${S3_BUCKET_FILES:zipt-files}

# Actuator 모니터링
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}

# Swagger
springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
  api-docs:
    path: /api/v3/api-docs
  webjars:
    prefix: /api/webjars            # UI가 로드하는 리소스도 /api 밑으로

#층간소음
#app:
#  environment:
#    api-key: 0b0da12b6428e8730e766b05eb00c721a79dfe5c5b929bec5546f55f521eefab
#    api-url: /15093156/v1/uddi:8b59bcd7-1c11-47b6-a1a3-905acdc29527

zipt:
  terms:
    s3-key: seed/terms.json
    admin-token: ${ZIP_ADMIN_TOKEN:zipt-temp-token-2026}
  guides:
    s3-key: seed/guides.json
    seed-location: classpath:seed/guides.json
    admin-token: ${ZIP_ADMIN_TOKEN:zipt-temp-token-2026}
  # Redis 설정
  redis:
    cache-database: 1
    blacklist-database: 0

# JWT - 20260629 동혁 (공통 yml로 관리 - dev, prod)
jwt:
  secret: ${JWT_SECRET:rREsXlcKqhtDBG5s2M015wnDs3dWTbL0KXlshU3OHJQ}
  expiration: 720000000

# pool-size 늘림

